export const NETWORKS = [
    {
      value: "ethereum",
      label: "Ethereum",
      chainId: 1,
      gnosisPrefix: "eth",
      logo: "networks/ethereum.ico",
    },
    {
      value: "arbitrum",
      label: "Arbitrum",
      chainId: 42161,
      gnosisPrefix: "arb1",
      logo: "networks/arbitrum.ico",
    },
    {
      value: "optimism",
      label: "OP Mainnet",
      chainId: 10,
      gnosisPrefix: "oeth",
      logo: "networks/optimism.ico",
    },
    {
      value: "base",
      label: "Base",
      chainId: 8453,
      gnosisPrefix: "base",
      logo: "networks/base.ico",
    },
    {
      value: "worldchain",
      label: "Worldchain",
      chainId: 10252,
      gnosisPrefix: "wc",
      logo: "networks/worldchain.ico",
    },
    {
      value: "unichain",
      label: "Unichain",
      chainId: 130,
      gnosisPrefix: "unichain",
      logo: "networks/unichain.ico",
    },
    {
      value: "berachain",
      label: "Berachain",
      chainId: 80094,
      gnosisPrefix: "berachain",
      logo: "networks/berachain.ico",
    },
    {
      value: "sonic",
      label: "Sonic",
      chainId: 146,
      gnosisPrefix: "sonic",
      logo: "networks/sonic.ico",
    },
    {
      value: "ink",
      label: "Ink",
      chainId: 57073,
      gnosisPrefix: "ink",
      logo: "networks/ink.ico",
    },
    {
      value: "mantle",
      label: "Mantle",
      chainId: 5000,
      gnosisPrefix: "mnt",
      logo: "networks/mantle.ico",
    },
    {
      value: "polygon",
      label: "Polygon",
      chainId: 137,
      gnosisPrefix: "matic",
      logo: "networks/polygon.ico",
    },
    {
      value: "bsc",
      label: "BSC",
      chainId: 56,
      gnosisPrefix: "bnb",
      logo: "networks/bsc.ico",
    },
    {
      value: "avalanche",
      label: "Avalanche",
      chainId: 43114,
      gnosisPrefix: "avax",
      logo: "networks/avalanche.ico",
    },
    {
      value: "celo",
      label: "Celo",
      chainId: 42220,
      gnosisPrefix: "celo",
      logo: "networks/celo.ico",
    },
    {
      value: "gnosis",
      label: "Gnosis Chain",
      chainId: 100,
      gnosisPrefix: "gno",
      logo: "networks/gnosis.ico",
    },
    {
      value: "linea",
      label: "Linea",
      chainId: 59144,
      gnosisPrefix: "linea",
      logo: "networks/linea.ico",
    },
    {
      value: "zksync",
      label: "zkSync",
      chainId: 324,
      gnosisPrefix: "zksync",
      logo: "networks/zksync.ico",
    },
    {
      value: "polygon-zkevm",
      label: "Polygon zkEVM",
      chainId: 1101,
      gnosisPrefix: "zkevm",
      logo: "networks/polygon.ico",
    },
    {
      value: "scroll",
      label: "Scroll",
      chainId: 534352,
      gnosisPrefix: "scr",
      logo: "networks/scroll.ico",
    },
    {
      value: "xlayer",
      label: "xLayer",
      chainId: 204,
      gnosisPrefix: "xlayer",
      logo: "networks/xlayer.ico",
    },
    {
      value: "aurora",
      label: "Aurora",
      chainId: 1313161554,
      gnosisPrefix: "aurora",
      logo: "networks/aurora.ico",
    },
    {
      value: "blast",
      label: "Blast",
      chainId: 81457,
      gnosisPrefix: "blast",
      logo: "networks/blast.ico",
    },
    {
      value: "sepolia",
      label: "Sepolia",
      chainId: 11155111,
      gnosisPrefix: "sep",
      logo: "networks/ethereum.ico",
    },
    {
      value: "base-sepolia",
      label: "Base Sepolia",
      chainId: 84532,
      gnosisPrefix: "basesep",
      logo: "networks/base.ico",
    },
    {
      value: "gnosis-chiado",
      label: "Gnosis Chiado",
      chainId: 10200,
      gnosisPrefix: "chiado",
      logo: "networks/gnosis.ico",
    }
  ];


export const SAFE_VERSIONS = [
  "0.0.1",
  "0.1.0",
  "1.0.0",
  "1.1.0",
  "1.1.1",
  "1.2.0",
  "1.3.0",
  "1.4.1"
];

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";