export const NETWORKS = [
    {
      value: "arbitrum",
      label: "Arbitrum",
      chainId: 42161,
      gnosisPrefix: "arb1",
      logo: "networks/arbitrum.ico",
    },
    {
      value: "aurora",
      label: "Aurora",
      chainId: 1313161554,
      gnosisPrefix: "aurora",
      logo: "networks/aurora.ico",
    },
    {
      value: "avalanche",
      label: "Avalanche",
      chainId: 43114,
      gnosisPrefix: "avax",
      logo: "networks/avalanche.ico",
    },
    {
      value: "base",
      label: "Base",
      chainId: 8453,
      gnosisPrefix: "base",
      logo: "networks/base.ico",
    },
    {
      value: "base-sepolia",
      label: "Base Sepolia",
      chainId: 84532,
      gnosisPrefix: "basesep",
      logo: "networks/base.ico",
    },
    {
      value: "blast",
      label: "Blast",
      chainId: 81457,
      gnosisPrefix: "blast",
      logo: "networks/blast.ico",
    },
    {
      value: "bsc",
      label: "BSC",
      chainId: 56,
      gnosisPrefix: "bnb",
      logo: "networks/bsc.ico",
    },
    {
      value: "celo",
      label: "Celo",
      chainId: 42220,
      gnosisPrefix: "celo",
      logo: "networks/celo.ico",
    },
    {
      value: "ethereum",
      label: "Ethereum",
      chainId: 1,
      gnosisPrefix: "eth",
      logo: "networks/ethereum.ico",
    },
    {
      value: "gnosis",
      label: "Gnosis Chain",
      chainId: 100,
      gnosisPrefix: "gno",
      logo: "networks/gnosis.ico",
    },
    {
      value: "gnosis-chiado",
      label: "Gnosis Chiado",
      chainId: 10200,
      gnosisPrefix: "chiado",
      logo: "networks/gnosis.ico",
    },
    {
      value: "linea",
      label: "Linea",
      chainId: 59144,
      gnosisPrefix: "linea",
      logo: "networks/linea.ico",
    },
    {
      value: "mantle",
      label: "Mantle",
      chainId: 5000,
      gnosisPrefix: "mnt",
      logo: "networks/mantle.ico",
    },
    {
      value: "optimism",
      label: "OP Mainnet",
      chainId: 10,
      gnosisPrefix: "oeth",
      logo: "networks/optimism.ico",
    },
    {
      value: "polygon",
      label: "Polygon",
      chainId: 137,
      gnosisPrefix: "matic",
      logo: "networks/polygon.ico",
    },
    {
      value: "polygon-zkevm",
      label: "Polygon zkEVM",
      chainId: 1101,
      gnosisPrefix: "zkevm",
      logo: "networks/polygon.ico",
    },
    {
      value: "scroll",
      label: "Scroll",
      chainId: 534352,
      gnosisPrefix: "scr",
      logo: "networks/scroll.ico",
    },
    {
      value: "sepolia",
      label: "Sepolia",
      chainId: 11155111,
      gnosisPrefix: "sep",
      logo: "networks/ethereum.ico",
    },
    {
      value: "worldchain",
      label: "Worldchain",
      chainId: 10252,
      gnosisPrefix: "wc",
      logo: "networks/worldchain.ico",
    },
    {
      value: "xlayer",
      label: "xLayer",
      chainId: 204,
      gnosisPrefix: "xlayer",
      logo: "networks/xlayer.ico",
    },
    {
      value: "zksync",
      label: "zkSync",
      chainId: 324,
      gnosisPrefix: "zksync",
      logo: "networks/zksync.ico",
    },
  ];